# Generated by Django 2.1.5 on 2019-01-11 13:07

from django.conf import settings
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True, validators=[students.validators.validate_section])),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=9999, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
