# Generated by Django 2.1.5 on 2019-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='extra_content',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='father_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='school',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
