# Generated by Django 2.1.5 on 2019-01-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190111_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='mothers_name',
            new_name='mother_name',
        ),
    ]
