# Generated by Django 2.1.5 on 2019-01-11 18:27

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190111_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=students.models.get_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
