# Generated by Django 2.1.5 on 2019-02-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlinfo',
            name='name',
        ),
    ]
