# Generated by Django 2.1.5 on 2019-03-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurl', '0003_twminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='twminfo',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
