# Generated by Django 2.1.5 on 2019-01-22 19:11

from django.db import migrations, models
import twitter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_accountinfo_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content', models.TextField(default='-')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=twitter.models.get_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete='CASCADE', to='accounts.AccountInfo')),
            ],
        ),
    ]
