# Generated by Django 2.1.5 on 2019-01-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20190122_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetinfo',
            name='owner',
            field=models.ForeignKey(on_delete='CASCADE', to='accounts.AccountInfo'),
        ),
    ]
