# Generated by Django 2.1.5 on 2019-01-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20190122_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetinfo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter.TweetInfo'),
        ),
        migrations.AlterField(
            model_name='tweetinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountInfo'),
        ),
    ]
