# Generated by Django 2.1.5 on 2019-01-24 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0004_auto_20190124_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetinfo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liking', to=settings.AUTH_USER_MODEL),
        ),
    ]
