# Generated by Django 2.1.5 on 2019-01-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_tweetinfo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetinfo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liking', to='accounts.AccountInfo'),
        ),
    ]
