# Generated by Django 2.1.5 on 2019-01-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
