# Generated by Django 2.1.5 on 2019-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arindhalE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arindhalcontributerinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
